#!/bin/sh

echo "Please talk to me ..."
while true
do
  read INPUT_STRING
  case $INPUT_STRING in
	hello)
		echo "Hello yourself!"
		;;
	bye)
		echo "See you again!"
		break
		;;
	*)
		echo "Sorry, I don't understand"
		;;
  	   esac
done
echo 
echo "That's all folks!"
#aqui ele pede pra você falar algo, se você disser "hello"(olá em inglês) ele dirá oi de volta, se disser tchau ele dirá tchau de volta, todavia se você 
#colocar texto o arquivo não tem dirá que não entendeu, após isso ele encerrará.
